### ISSUE TITLE
Typo in section w/ id="Datathons"

### ISSUE THREAD

**Issue by Draekus** [CriticalDatathon/criticaldatathon.github.io#1]
Noticed that one of your section titles has a typo. Says "form" but it should say "from". Just wanted to give a heads-up.
![image](https://user-images.githubusercontent.com/42391793/218193879-37bce5bb-9c48-4b3f-a821-55fc8f7a5cbd.png)

**Comment by joamats** [comment]
thanks @Draekus!!
